apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/akhan4u/argo-testing.git
    path: kyverno
    targetRevision: main
    directory:
      recurse: true
      exclude: "{*/kyverno-test.yaml,*/.chainsaw/*}"

# Exclude files in a directory structure
#   argo-testing/kyverno/
#   └── policies
#       ├── kyverno-test.yaml
#       └── require-non-root
#           ├── .chainsaw
#           │   ├── bad.yaml
#           │   ├── chainsaw-test.yaml
#           │   ├── good.yaml
#           │   └── policy-ready.yaml
#           └── require-non-root.yaml
