apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-kyverno
  namespace: argocd
spec:
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  source:
    path: helm/kyverno
    repoURL: https://github.com/akhan4u/argo-testing.git
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
